ALTER TABLE usuario
ADD COLUMN tipo VARCHAR(20) NOT NULL DEFAULT 'ROLE_USUARIO',
ADD COLUMN posto_id VARCHAR(255) NULL;

ALTER TABLE usuario
ADD CONSTRAINT fk_posto
FOREIGN KEY (posto_id) REFERENCES posto(id);